apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: localhost:5000/voufi/demo:6
        ports:
        - containerPort: 8087
        env:
        - name: CONFIG_SOURCE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: source-service-configmap
              key: service_url
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
#      nodePort: 30000